# This can be overriden by the file ~/.config/jdp/data.toml
datadir = "~/data"

# DB host name and auth token
host = "127.0.0.1"
auth = ""

# DB master node to replicate cached test data from if this is not the master
# node. These settings only work if you allow JDP to start your local Redis
# instance.
master-host = ""
master-auth = ""
