# Tracker definitions
#
# This file is merged with the contents of ~/.config/jdp/trackers.toml. The
# values defined there will win if there is a conflict. For example your
# trackers.toml file may look like:
#
# [instances]
# [instances.osd]
# apikey = "1234567890ABCDEF"
# apisecret = "1234567890ABCDEF"


# Tracker API definitions
[apis]

[apis.Bugzilla]
get-item-html = "/show_bug.cgi?id={id}"

[apis.Redmine]
get-item-html = "/issues/{id}"

[apis.OpenQA]
get-item-html = "/tests/{id}"

# Instances of trackers
[instances]

[instances.bsc]
api = "Bugzilla"
host = "apibugzilla.suse.com"
# It is recommended you set these in ~/.config/jdp/trackers.toml
#user = ""
#pass = ""

[instances.boo]
api = "Bugzilla"
host = "apibugzilla.opensuse.org"
#apikey = ""
#apisecret = ""

[instances.poo]
api = "Redmine"
host = "progress.opensuse.org"

[instances.t]
api = "OpenQA"

[instances.osd]
api = "OpenQA"
host = "openqa.suse.de"

[instance.o3]
api = "OpenQA"
host = "openqa.opensuse.org"
