# Bug tracker definitions

[bsc]
api = "Bugzilla"
host = "apibugzilla.suse.com"
# Be careful not to commit your password to git if you set this!
#user = ""
#pass = ""

[poo]
api = "Redmine"
host = "progress.opensuse.org"
