#!BuildTag: JDP
FROM opensuse/tumbleweed:latest

LABEL name=jdp-base maintainer=rpalethorpe@suse.com description="JDP baseline installation"

ARG JULIA_VER=1.1.0
ARG JULIA_TAR=install/julia-${JULIA_VER}-linux-x86_64.tar.gz

# TODO: We should really install the official SUSE Julia package now, but some 3rd
# numerical libraries have compilation issues with other libraries and... well
# we just install from tar ball for now.
# RUN zypper in julia
RUN zypper ar -Gf https://download.opensuse.org/repositories/devel:/openQA/openSUSE_Leap_15.1 oqa
RUN zypper in -y curl tar gzip bzip2 python3-jupyter python3-jupyter_nbconvert \
    	      	 python3-jupyter_client python3-jupyter_notebook redis mailx
RUN zypper in -y --from oqa openQA-client
RUN zypper clean --all

# There is no default non-root user in the Tumbleweed image, so we create one
# because doing everything as root unecessarily is probably immoral or something
RUN useradd -m -g users jdp

# CD to the new user's home directory
WORKDIR /home/jdp

# Copy the whole project into the container
COPY --chown=jdp:users ./ ./src

# su jdp
USER jdp
# Put the user's bin dir in the path so that we do not have to touch any system files
ENV PATH=/home/jdp/bin:${PATH}

# Install julia from the official tarball. Obviously this is very naughty and should be
# replaced with the Julia package at some point
RUN mkdir data
RUN mkdir julia && cd julia && tar -xzf ../src/$JULIA_TAR
RUN ln -s ~/julia/julia-$JULIA_VER/bin/julia ~/bin/julia

# Cache the current JDP dependencies. This will be overwritten.
RUN ["julia", "--color=yes", "src/install/install.jl"]
