#!BuildTag: JDP
FROM jdp:latest

LABEL name=jdp-slave maintainer=rpalethorpe@suse.com description="JDP with production config"

ARG REDIS_MASTER_HOST="redis"
ARG REDIS_MASTER_AUTH="notsecret"

RUN mkdir -p ~/.config/jdp
RUN echo "master-host = \"$REDIS_MASTER_HOST\"" > ~/.config/jdp/data.toml
RUN echo "master-auth = \"$REDIS_MASTER_AUTH\"" >> ~/.config/jdp/data.toml

