# See gitlab-ci.md and Dockerfile

before_script:
  - pwd && ls -l
  - docker network create production || true
  - 'echo Container labels: $DOM.job_id=$CI_JOB_ID, $DOM.commit=$CI_COMMIT_SHA'

variables:
  DOM: "de.suse.gitlab"

stages:
  - build
  - test
  - deploy
  - execute

.make:
  tags:
    - primary
  except:
    - schedules

build:
  stage: build
  extends: .make
  script:
    - >
      docker build --label $DOM.job_stage=$CI_JOB_STAGE
      --label $DOM.job_id=$CI_JOB_ID --label $DOM.commit=$CI_COMMIT_SHA
      -t jdp:$CI_COMMIT_SHA -f install/Dockerfile ./

test:
  stage: test
  extends: .make
  script:
    - >
      docker run --label $DOM.job_stage=$CI_JOB_STAGE
      --label $DOM.job_id=$CI_JOB_ID --label $DOM.commit=$CI_COMMIT_SHA
      -t jdp:$CI_COMMIT_SHA julia --color=yes ../install/test.jl

deploy:
  stage: deploy
  extends: .make
  environment:
    name: production
  when: manual
  only:
    - master
  script:
    - docker tag jdp:$CI_COMMIT_SHA jdp:latest
    - >
      docker build
      --label $DOM.job_stage=$CI_JOB_STAGE --label $DOM.job_id=$CI_JOB_ID
      -t jdp:production -f install/Dockerfile-production
      --build-arg REDIS_AUTH=$REDIS_MASTER_PASS ./

publish:
  stage: execute
  extends: .make
  when: manual
  only:
    - master
  script:
    - docker tag jdp:latest suserichiejp/jdp:latest
    - docker push suserichiejp/jdp:latest

.start-redis:
  stage: execute
  except:
    - schedules
  when: manual
  script:
    - docker stop -t 30 redis || true
    - docker rm redis || true
    - >
      docker run --name redis --network production -d -p 6379:6379
      -v ~/data:/home/jdp/data jdp:production
      /usr/sbin/redis-server /home/jdp/.config/redis/master.conf

start-redis-us:
  extends: .start-redis
  environment:
    name: redis-master-us
    on_stop: stop-redis-us
  tags:
    - America

start-redis-eu:
  extends: .start-redis
  environment:
    name: redis-master-eu
    on_stop: stop-redis-eu
  tags:
    - Europe

.stop-redis:
  stage: execute
  except:
    - schedules
  when: manual
  script:
    - docker stop -t 30 redis

stop-redis-us:
  extends: .stop-redis
  environment:
    name: redis-master-us
    action: stop
  tags:
    - America

stop-redis-eu:
  extends: .stop-redis
  environment:
    name: redis-master-eu
    action: stop
  tags:
    - Europe

pages:
  stage: execute
  tags:
    - primary
  environment:
    name: production
  only:
    - schedules
  artifacts:
    paths:
      - public
  script:
    - docker stop report || true
    - docker rm -f report || true
    - mkdir -p public/reports
    - >
      docker run --name report --network production -t
      --mount type=bind,src=$(pwd)/public,target=/home/jdp/data jdp:production
      julia --color=yes run/all.jl
    - >
      docker run --label $DOM.job_stage=$CI_JOB_STAGE
      --label $DOM.job_id=$CI_JOB_ID --label $DOM.commit=$CI_COMMIT_SHA
      --mount type=bind,src=$(pwd)/public,target=/home/jdp/src/docs/build
      -t jdp:production julia --color=yes docs/build.jl

after_script:
  - ls -l
  - docker ps --all -f label=$DOM.job_id=$CI_JOB_ID -f label=$DOM.commit=$CI_COMMIT_SHA
  - docker images --all -f label=$DOM.job_id=$CI_JOB_ID -f label=$DOM.commit=$CI_COMMIT_SHA
  - julia --color=yes install/container-housecleaning.jl
