# See gitlab-ci.md and Dockerfile

variables:
  JULIA_VER: '1.0.3'
  JULIA_URI: '~/julia-$JULIA_VER-linux-x86_64.tar.gz'

before_script:
  - pwd && ls -l
  - docker ps --all
  - docker images --all

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t jdp -f install/Dockerfile --build-arg juliav=$JULIA_VER --build-arg tarurl=$JULIA_URI ./

test:
  stage: test
  script:
    - docker run -it jdp julia install/test.jl

docs:
  stage: deploy
  script:
    - docker run -it jdp julia docs/build.jl

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
