before_script:
  - echo "Before Script"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building..."

docs:
  stage: build
  script:
    - echo "Building docs..."

test:
  stage: test
  script:
    - echo "Testing..."

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
