# See gitlab-ci.md and Dockerfile

before_script:
  - pwd && ls -l
  - docker ps --all
  - docker images --all
  - 'echo Container labels: $DOM.job_id=$CI_JOB_ID, $DOM.commit=$CI_COMMIT_SHA'

variables:
  DOM: "de.suse.gitlab"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build --label $DOM.job_stage=$CI_JOB_STAGE --label $DOM.job_id=$CI_JOB_ID --label $DOM.commit=$CI_COMMIT_SHA -t jdp:$CI_COMMIT_SHA -f install/Dockerfile ./

test:
  stage: test
  script:
    - docker run --label $DOM.job_stage=$CI_JOB_STAGE --label $DOM.job_id=$CI_JOB_ID --label $DOM.commit=$CI_COMMIT_SHA -t jdp:$CI_COMMIT_SHA julia ../install/test.jl

docs:
  stage: deploy
  script:
    - docker run --label $DOM.job_stage=$CI_JOB_STAGE --label $DOM.job_id=$CI_JOB_ID --label $DOM.commit=$CI_COMMIT_SHA -t jdp:$CI_COMMIT_SHA julia ../docs/build.jl

deploy:
  stage: deploy
  environment:
    name: production
  when: manual
  only:
    - master
  script:
    - docker tag jdp:$CI_COMMIT_SHA jdp:latest

deploy-redis:
  stage: deploy
  environment:
    name: redis-master
    on_stop: stop-redis
  when: manual
  script:
    - docker stop -t 30 redis || true
    - docker rm redis || true
    - docker run --name redis -d -p 6379:6379 -v ~/data:/home/jdp/data jdp:latest /usr/sbin/redis-server ../conf/redis-master.conf --requirepass $REDIS_MASTER_PASS

stop-redis:
  stage: deploy
  environment:
    name: redis-master
    action: stop
  when: manual
  script:
    - docker stop -t 30 redis

after_script:
  - ls -l
  - docker ps --all -f label=$DOM.job_id=$CI_JOB_ID -f label=$DOM.commit=$CI_COMMIT_SHA
  - docker images --all -f label=$DOM.job_id=$CI_JOB_ID -f label=$DOM.commit=$CI_COMMIT_SHA
