before_script:
  - pwd && ls -l
  - docker ps --all
  - docker images --all

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t jdp -f install/Dockerfile

test:
  stage: test
  script:
    - docker run -it jdp julia install/test.jl

docs:
  stage: deploy
  script:
    - docker run -it jdp julia docs/build.jl

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
