# See gitlab-ci.md and Dockerfile

before_script:
  - pwd && ls -l
  - docker ps --all
  - docker images --all

variables:
  DOM: "de.suse.gitlab"
  LABELS: "--label $DOM.job_id=$CI_JOB_ID --label $DOM.commit=$CI_COMMIT_SHA"
  FILTER: "-f label=$DOM.job_id=$CI_JOB_ID -f label=$DOM.commit=$CI_COMMIT_SHA"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build $META --label $DOM.job_stage=$CI_JOB_STAGE -t jdp -f install/Dockerfile ./

test:
  stage: test
  script:
    - docker run $META --label $DOM.job_stage=$CI_JOB_STAGE -it jdp julia install/test.jl

docs:
  stage: deploy
  script:
    - docker run $META --label $DOM.job_stage=$CI_JOB_STAGE -it jdp julia docs/build.jl

deploy:
  stage: deploy
  script:
    - echo "Deploying..."

after_script:
  - ls -l
  - docker ps --all $FILTER
  - docker images --all $FILTER
