before_script:
  - pwd && ls -l
  - docker network create production || true

variables:
  DOM: "de.suse.gitlab"

.make:
  tags:
    - primary
  except:
    - schedules

after_script:
  - ls -l
  - docker ps --all -f label=$DOM.job_id=$CI_JOB_ID -f label=$DOM.commit=$CI_COMMIT_SHA
  - docker images --all -f label=$DOM.job_id=$CI_JOB_ID -f label=$DOM.commit=$CI_COMMIT_SHA
  - julia --color=yes install/container-housecleaning.jl
